Yoo ran/3 create form for upload property
yoo-ran/goldenkey pull request #15
Opened 2024-10-02 21:26 UTC by yoo-ran

Debug and finalize the property submission form, excluding the address section. A separate task will handle the address inputs (#14).

2024-10-04 17:19 UTC, haejoonchoi commented
UI change가 혹시 있으면 웹사이트에서 어느 부분에 UI Change 있는 지 혹시 스크린샷을 첨부해주실수 있나요?

2024-10-15 17:03 UTC, yoo-ran commented
> UI change가 혹시 있으면 웹사이트에서 어느 부분에 UI Change 있는 지 혹시 스크린샷을 첨부해주실수 있나요?

# 변경전
![Screenshot 2024-10-15 at 10 02 13 AM](https://github.com/user-attachments/assets/888d3120-1704-41f0-9970-09905233bc89)

# 변경후
![Screenshot 2024-10-15 at 10 02 38 AM](https://github.com/user-attachments/assets/ec500263-0a44-4b1e-8fcb-d7ac478d24b9)

- 만원버튼 추가, 백그라운드와 인풋 컬러 변경

2024-10-23 19:47 UTC, haejoonchoi requested changes

2024-10-24 19:10 UTC, yoo-ran commented on backend/server.js
> -                item['이름'],
@haejoonchoi 
연락처라는 컬럼이름을 하나 생성하고 그안에 매도인, 매수인, 부동산의 연락처와 이름을 한번에 json으로 저장했습니다.

2024-10-24 19:11 UTC, yoo-ran commented on frontend/src/routes/Detail.jsx
> +            const response = await axios.get(`http://localhost:8000/detail/4`);
@haejoonchoi 
테스트차 임의로 대입했습니다.
마지막에 변수로 변경할 예정입니다.

2024-10-24 19:24 UTC, yoo-ran commented on backend/server.js
> -    const imagePaths = req.files.map(file => file.path); // Get the paths of uploaded images
@haejoonchoi 

올려주신 chatgpt에 따라 수정했습니다!

2024-10-24 19:30 UTC, yoo-ran commented on frontend/src/routes/Detail.jsx
>      console.log(propertyData);
@haejoonchoi 

첫번째 방법인 useEffect를 이용하여 console.log를 사용하였습니다.

2024-10-28 19:06 UTC, merged